#!/bin/bash
set -e

: "${AIRFLOW_DB_USER:?Missing AIRFLOW_DB_USER}"
: "${AIRFLOW_DB_PASSWORD:?Missing AIRFLOW_DB_PASSWORD}"
: "${AIRFLOW_DB:?Missing AIRFLOW_DB}"
: "${MOVIE_DB_USER:?Missing MOVIE_DB_USER}"
: "${MOVIE_DB_PASSWORD:?Missing MOVIE_DB_PASSWORD}"
: "${MOVIE_DB:?Missing MOVIE_DB}"

echo "Creating Airflow database and user..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE USER $AIRFLOW_DB_USER WITH PASSWORD '$AIRFLOW_DB_PASSWORD';
CREATE DATABASE $AIRFLOW_DB OWNER $AIRFLOW_DB_USER;
GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB TO $AIRFLOW_DB_USER;
EOSQL

echo "Creating Movie database and user..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE USER $MOVIE_DB_USER WITH PASSWORD '$MOVIE_DB_PASSWORD';
CREATE DATABASE $MOVIE_DB OWNER $MOVIE_DB_USER;
GRANT ALL PRIVILEGES ON DATABASE $MOVIE_DB TO $MOVIE_DB_USER;
EOSQL

echo "Postgres initialization finished."
