FROM postgres:15

# Set working dir
WORKDIR /docker-entrypoint-initdb.d

# Copy init script
COPY ./scripts/docker-entrypoint-init/postgres_init/postgres_init.sh .

# Set execute permission
RUN chmod +x postgres_init.sh

# Convert line ending '\r'
RUN sed -i 's/\r$//' postgres_init.sh
